package br.com.fitcontrol.fitcontrol.events;

public enum EnumEventTypes {
    EVENT_TYPE_ACESS_CHECK_IN,
    EVENT_TYPE_ACESS_CHECK_OUT,
    EVENT_TYPE_PAYMENT_REGISTER_PAYMENT,
    EVENT_TYPE_PAYMENT_UPDATE_PAYMENT,
    EVENT_TYPE_PAYMENT_DELETE_PAYMENT,
    EVENT_TYPE_CATRACA_REGISTER,
    EVENT_TYPE_CATRACA_UPDATE,
    EVENT_TYPE_CATRACA_DELETE,
    EVENT_TYPE_REPORT_REQUEST_REPORT,
    EVENT_TYPE_REWARD_REGISTER,
    EVENT_TYPE_REWARD_UPDATE,
    EVENT_TYPE_REWARD_DELETE,
    EVENT_TYPE_USER_REGISTER,
    EVENT_TYPE_USER_UPDATE,
    EVENT_TYPE_USER_DELETE,
    EVENT_TYPE_CATRACA_ERRO,
    EVENT_TYPE_Employee_Register,
    EVENT_TYPE_Employee_Update,
    EVENT_TYPE_Employee_Delete
}
